---
output:
    size_x: 1872
    size_y: 1404
    image_type: "L"
    background: white

tiles:
    bandwidth:
        x: 520
        y: 1025
        size_x: 700
        size_y: 375

    calendar:
        sources:
            - fg: 255
              symbol: ⚒
              bg: 120
              url: http://mail.tallwireless.com/cal.ics
            - fg: 0
              symbol: ⌂
              bg: 220
              url: https://calendar.google.com/calendar/ical/rumford.charles%40gmail.com/private-499bf5ead81dcfbbe5f838050fa2aca0/basic.ics
        x: 520
        y: 10
        size_x: 872
        size_y: 1000
        cache: 30
    clock:
        x: 10
        y: 10
        size_x: 500
        size_y: 1404
        border_width: 10
        alignment: vertical
        incremental_update: true
        border:
            right:
                width: 5
                interval: 20
        cities:
            Philly: US/Eastern
            Chicago: US/Central
            UTC: UTC
