---
output:
    size_x: 1872
    size_y: 1404
    image_type: "L"
    background: white

tiles:
    clock:
        x: 10
        y: 10
        size_x: 600
        size_y: 1404
        border_width: 10
        alignment: vertical
        border:
            right:
                width: 5
                interval: 20
        cities:
            Philly: US/Eastern
            Chicago: US/Central
            UTC: UTC
